### ISSUE TITLE
Improve Previous program, Fix,Documentation, Readability 

### ISSUE THREAD

**Issue by DrakeEntity** [Py-Contributors/Hacktoberfest-2020#6]
Before contributing Please Check [Readme.md](https://github.com/Py-Contributors/Hacktoberfest-2020/blob/master/README.md)
Register yourself for [HacktoberFest](https://hacktoberfest.digitalocean.com/)

Best Of Luck
Happy Coding,

**Comment by VaibhaveS** [comment]
I would like to take up this issue. I have good competitive programming experience [ rated 1900+ on codechef ]

**Comment by codePerfectPlus** [comment]
Thanks, @VaibhaveS
Have you heard about HacktoberFest, If not then Check README.md.

This repository is for first time programmers & new to github user to encourage them to contribute to open source.It will be great for all of us If you will help us in this work.

### What Can You do?

- You can change Code for better performance, readability, new features, enhancement.
- You can contribute to documentation as well because Documentaion helps others to understand your program & Purpose.
- You can encourage new programmer to contribute to open source.
- Upload Your C++/Python/JS/TS/Java Code in Respective folder, If that doesn't exist create one.

### What will be reward ?

 Contributing to open-source is reward itself. Suppose a world without open-source. 
You can also win t-shirt for that, Check [Hacktobefest official website](https://hacktoberfest.digitalocean.com/)

Currently we don't have any repo for competitive programming except [HackerRank Algorithm](https://github.com/Py-Contributors/AlgorithmHackerRank) because we are more focused on ML, DL application.

Happy Coding,

**Comment by VaibhaveS** [comment]
Sure will try my best,
Thanks

**Comment by VaibhaveS** [comment]
Hello, 
Will it be useful if i add the programs which are currently in python to other languages such as C++?

**Comment by codePerfectPlus** [comment]
ya sure, Changing code from one language to other will be amazing fo learning prospective. 

#### Here are some tips.
- add them to new folder(C++)
- add documentation to program if it needs.

Happy Coding,

**Comment by mfonism** [comment]
Hi @DrakeEntity and @codePerfectPlus,

I really like the platform you've created here for Python beginners to get involved in Hacktoberfest 2020. Thank you so very much for this.

I just recently started teaching a group of people in my local community how to solve problems with Python, and I'm going to share this with them so they get their first experience with Open Source.

That said, I've read through the README, and I'm a little bothered by the part about (pull requests getting marked as invalid for being low effort)[https://github.com/Py-Contributors/Hacktoberfest-2020/blob/master/README.md#what-if-my-pull-requests-arent-accepted]. It would be demoralizing to newcomers if their pull requests get flagged that way.

In any case, I will work with my students on their changes before they submit PRs, so that they don't get spammy with it.

Once again, thank you for the amazing work you're doing.

**Comment by codePerfectPlus** [comment]
@mfonism Thanks, for checking out the Repo.

I am in HacktoberFest's Official discord server. Repository will be marked as blocked which has low effort. Like adding name in `README.md`. If it's look like that the above repository is not good enough for hacktoberFest then we have other projects too here. Consider them. 

#### What our objective for this Repository

- Improve programme efficiency ( Using `List Comprehension` instead of for loop)
- Improve documentation of program (if it's clear what's program is doing someone can add documentation to it)
- Improve `README.md` documentation ( sentence formation, grammatical mistakes etc)

So checking about objective I don't think it will be marked as low efforts.

### Other Projects in organization

FileMoverGUI - Autocleaning Download Folder, It will arrange pic, videos, zip according to there respective folder.
OpenCvTutorial - Computer vision library program written in Python

Before 1st october there will be 2 more repository for contributions.

Happy Coding,

**Comment by mfonism** [comment]
Thank you for clarifying.

**Comment by VidyaSrivatsan** [comment]
Hi,

I am interested to contribute towards documentation. How do search for issue specific to documentation?
